package com.sample

//list any import classes here.
import com.sample.*;


//declare any global variables here
global DroolsUtil droolsUtil;



rule "Your First Rule"
dialect "java" 
    when
        u : User()
    then
        User sampleUser =  droolsUtil.getSampleUser(10);
        if(sampleUser.getName().equalsIgnoreCase("Sample Username")){
        	System.out.println("Sample User Created Successfully");
        }else{
        	System.out.println("Sample User not created");
        }
end