//created on: 13/01/2013
package com.ebuild.leap.drools

//list any import classes here.
import com.ebuild.leap.pojo.ElementManifest;
import com.ebuild.leap.pojo.Element;
import java.util.List;



//declare any global variables here
global List targetElementManifest;
global ElementManifest currentElementManifest;

rule "For Every Element Insert ElementManifest"
    when
        $element : Element()
        $elementManifest : ElementManifest() from $element.elementManifestList
    then      
		insert($elementManifest);
end

rule "For Every ElementManifest Insert Element"
    when
        $elementManifest : ElementManifest()
    then
        insert($elementManifest.getChildElement());
end

rule "Update Manifest"
no-loop
dialect "mvel" 
	when
		$elementManifest : ElementManifest( id == currentElementManifest.id)
	then
		targetElementManifest.add($elementManifest);
end